import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useTina } from 'tinacms/dist/edit-state'
import Link from 'next/link'
import { getData } from '../lib/api'


const query = `{
  home(relativePath: "Principal.md"){
    title,
    body,
    image
  }
}`

export default function Home(props) {
  const { data } = useTina({
    query,
    variables: {},
    data: props.data,
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Next + Tina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          {data.home.title}
        </h1>

        <p className={styles.description}>
          {data.home.body}
        </p>

        <img src={data.home.image} width="300px" alt="logo" />

        <Link href="/rooms">
          <button>
            Ver Quartos
          </button>
        </Link>

      </main>
    </div>
  )
}


export async function getStaticProps(context) {
  const data = await getData("home", "Principal.md", "title, body, image");

  return {
    props: { data },
  }
}
