import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { staticRequest } from 'tinacms'
import { useTina } from 'tinacms/dist/edit-state'


const query = `{
  home(relativePath: "Principal.md"){
    title,
    body
  }
}`

export default function Home(props) {
  const { data } = useTina({
    query,
    variables: {},
    data: props.data,
  })

  console.log(data)

  return (
    <div className={styles.container}>
      <Head>
        <title>Next + Tina</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          {data.home.title}
        </h1>

        <p className={styles.description}>
          {data.home.body}
        </p>

      </main>
    </div>
  )
}


export async function getStaticProps(context) {
  let data = {}
  try {
    data = await staticRequest({
      query,
      variables: { relativePath: 'Principal.md' },
    })
  } catch {
    // swallow errors related to document creation
  }

  return {
    props: { data },
  }
}
